### ISSUE TITLE
Delete obsolete classes with typo 'dft'

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_LinearSystems2#10]
**Reported by tobolar on 25 Jun 2012 15:12 UTC**
Delete obsolete classes 
Modelica_LinearSystems2.DiscreteTransferFunction.'\*'.'dft\*dft'
Modelica_LinearSystems2.DiscreteTransferFunction.'\*'.'r\*dft'
Modelica_LinearSystems2.DiscreteTransferFunction.'/'.'dft/dft'
Modelica_LinearSystems2.DiscreteTransferFunction.'/'.'r/dft'

The corrected classes already exist in the library.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/765

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 14 Mar 2016 20:38 UTC**

**Comment by tobolar** [comment]
It seems to me to be already done, i.e. there exist no more classes listed above.
A necessary class converison for the version update is defined in `ConvertLinearSystems2_from_2.2.2_to_XXX.mos` as well.

**Comment by tobolar** [comment]
Duplicate, see #4
