### ISSUE TITLE
Return value of Modelica_LinearSystems2.ModelAnalysis.FullAnalysis using python interface 

### ISSUE THREAD

**Issue by MatthiasBSchaefer** [modelica/Modelica_LinearSystems2#116]
When performing a FullAnalysis of the  Modelica_LinearSystems2 package:
Modelica_LinearSystems2.ModelAnalysis.FullAnalysis
using the python interface of Dymola, i've troubles to receive the full information provided by this function, as it appears when doing it in the Dymola-GUI:

```
cmd='Modelica_LinearSystems2.ModelAnalysis.FullAnalysis("package.model.name")
result=dymolaInterface.ExecuteCommand(cmd)
_>>> result =['<html>', '<head>', '  <title>Analysis of a state space system from Modelica LinearSystems2</title>', '</head>', '<style type="text/css">', '* { font-size: 10pt; font-family: Arial,sans-serif; }', '</style>', '<p>', 'The system has no invariant zeros.', '</p>', '</html>']_

lastError=dymolaInterface.getLastError()
_>>> lastError = ['', 0, 0, 0]_
```
I expected to receive either the full html-code (including eigenvalues, linear matrix, ... ) or at least the location where the html-report is stored (which is the current directory) as "result" or as "lastError" variable (see code-example above)

**Comment by tobolar** [comment]
Actually, the printing into a file is done "ongoing" by single `print` commands. So i wonder there is even some response in `result`. But returning the location of the generated html file is a good idea.

**Comment by tobolar** [comment]
@MatthiasBSchaefer Please check if PR #172 resolves the issue.

**Comment by MatthiasBSchaefer** [comment]
@tobolar 
Hi Jakub,

Thanks for the update !
This works fine.

BR Matthias
