### ISSUE TITLE
Move Types under Utilities

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_LinearSystems2#13]
**Reported by tobolar on 5 Jul 2012 15:06 UTC**
Types contained in the package Modelica_LinearSystems2.Types should be moved into package Modelica_LinearSystems2.Utilities.Types.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/771

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 14 Mar 2016 20:38 UTC**

**Comment by tobolar** [comment]
Package reintroduced in 465697bf6f06c3cf9570f9794dbf0fb5eaf56625 for backward compatibility. Shall be deleted for new version.

**Comment by tobolar** [comment]
A conversion was already introduced in `ConvertLinearSystems2_from_2.3.4.mos`. Thus, the obsolete package Modelica_LinearSystems2.Types can be deleted.
