### ISSUE TITLE
Broken class links

### ISSUE THREAD

**Issue by m-kessler** [modelica/Modelica_LinearSystems2#170]
There are some broken links to other Modelica classes in current HEAD 8ce9333747d150a9366d069beb90ff274837b53c of master:

| Class                                                                       |  Link                                                                            |
|---------------------------------------------------------------------------- | -------------------------------------------------------------------------------- |
| `Modelica_LinearSystems2.Controller.PID`                                    |  modelica://Modelica.Blocks.Types.InitPID                                        |
| `Modelica_LinearSystems2.Controller.LimPID`                                 |  modelica://Modelica.Blocks.Types.InitPID                                        |
| `Modelica_LinearSystems2.Math.Matrices.householderReflexion`                |  modelica://Modelica.Math.Matrices.Utilities.householderSimilarityTransformation |
| `Modelica_LinearSystems2.Math.Matrices.householderSimilarityTransformation` |  modelica://Modelica.Math.Matrices.Utilities.householderReflection               |

**Comment by tobolar** [comment]
Checklist

- [ ] `Modelica_LinearSystems2.Controller.PID`: modelica://Modelica.Blocks.Types.InitPID
- [ ] `Modelica_LinearSystems2.Controller.LimPID`: modelica://Modelica.Blocks.Types.InitPID
- [ ] `Modelica_LinearSystems2.Math.Matrices.householderReflexion`: modelica://Modelica.Math.Matrices.Utilities.householderSimilarityTransformation
- [ ] `Modelica_LinearSystems2.Math.Matrices.householderSimilarityTransformation`: modelica://Modelica.Math.Matrices.Utilities.householderReflection
