### ISSUE TITLE
Improve/fix documentation of Modelica_LinearSystems2

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_LinearSystems2#2]
**Modified by dietmarw on 12 Feb 2010 09:21 UTC**
See attached [raw-attachment:Modelica_LinearSystems2_StyleCheckLog.html StyleCheckLog.html] for indicators what needs to be improved/fixed.

----

**Reported by dietmarw on 12 Feb 2010 09:20 UTC**
See attached [raw-attachement:Modelica_LinearSystems2_StyleCheckLog.html StyleCheckLog.html] for indicators what needs to be improved/fixed.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/275

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 12 Feb 2010 09:21 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 26 Oct 2010 06:10 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 25 Jul 2012 16:26 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 2 Jan 2013 22:19 UTC**
This ticket is a ticket for library Modelica_LinearSystems2 and not for MSL3.2.1. Therefore, the milestone MSL3.2.1 is wrong and is changed to "undecided.

**Comment by modelica-trac-importer** [comment]
**Changelog removed by otter on 2 Jan 2013 22:19 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 22 Mar 2013 16:14 UTC**
The attachment seems to be no longer available (error message when trying to open it).

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 22 Mar 2013 18:13 UTC**
Repaired the attachment.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 14 Mar 2016 20:38 UTC**

**Comment by tbeu** [comment]
The link to http://www.itea2.org/public/project_leaflets/EUROSYSLIB_profile_oct-07.pdf from Modelica_LinearSystems2.Controller.UsersGuide.Contact yields 404.
