### ISSUE TITLE
proper outcome of FullAnalysis for models without states

### ISSUE THREAD

**Issue by MatthiasBSchaefer** [modelica/Modelica_LinearSystems2#260]
Obviously it doesn't really make sense to apply the Modelica_LinearSystems2.ModelAnalysis.FullAnalysis on models without any continuous time states. 
But i am using the library inside regression tests and it's some additional effort to check the number of time states a priori.

So i would appreciate a proper result (e.g. empty tables without any eigenvalues, etc. in the html),  but instead the command itself fails.
Till Modelica_LinearSystems2 2.4.0 this failure occured very fast with error message :  
"Failed to expanded subscripted expression: ss.xNames[1]"
but with version 3.0.0 there are several attemps to compile Modelica.Utilities.Streams.readRealMatrix which fail due to the empty eigenvalue matrix and it takes quite a lot of time. (Unhandled exception at 0x00A71584 in Modelica.Utilities.Streams.readRealMatrix.exe: 0xC0000094: Integer division by zero.)

As mentioned above i would suggest to interrupt the procedure in case of a model without states after reading dslin.mat and write some dummy-report.

**Comment by tobolar** [comment]
@MatthiasBSchaefer Could you provide an example model?

**Comment by MatthiasBSchaefer** [comment]
@tobolar Thanks for your response !
An example is the MSL example Modelica.StateGraph.Examples.ShowExceptions

A full linear analysis fails in this case.

**Comment by tobolar** [comment]
> So i would appreciate a proper result (e.g. empty tables without any eigenvalues, etc. in the html)...

In case of nx=0 (i.e. no states), I would prefer to simply prompt a corresponding message and break the analysis.

**Comment by MatthiasBSchaefer** [comment]
That's fine for me.

**Comment by tobolar** [comment]
@MatthiasBSchaefer Please check #262

**Comment by MatthiasBSchaefer** [comment]
@tobolar  Thank you for the fix !

Would it be possible to have this info-string as return value of the function-call instead of only prompt it to the command line ?:
`return_value = Modelica_LinearSystems2.ModelAnalysis.FullAnalysis("Modelica.StateGraph.Examples.ShowExceptions");`
==> return_value is currently an empty string 
instead i propse to have:
return_value = "The system has no continuous states. No analysis performed."

This is principally the same wish i already had in https://github.com/modelica/Modelica_LinearSystems2/issues/116

**Comment by tobolar** [comment]
@MatthiasBSchaefer With a6aa1c7fb8b65803d09ee8a0da22eb5561b0d988, a report is generated as usual with a corresponding message in *Description* section. All following analyses are break.

**Comment by MatthiasBSchaefer** [comment]
@tobolar 
Thank you for this improvement !
It is working well.
Your idea to return an additional integer indicating the "state of outcome" would also be a worthy information: e.g. 
(state_of_outcome, report_file ) = Modelica_LinearSystems2.ModelAnalysis.FullAnalysis("Modelica.StateGraph.Examples.ShowExceptions");
