### ISSUE TITLE
Error in Modelica_LinearSystems2.TransferFunction.Plot.polesAndZeros

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_LinearSystems2#31]
**Reported by hansolsson on 17 Jun 2015 08:07 UTC**
The call:
StateSpace.Plot.polesAndZeros(StateSpace(tf), poles, zeros, defaultDiagram, device);
does not match the called function - the argument 'print' is missing between zeros and defaultDiagram

In version:
2.3.2, 2015-04-17, build 2 (2014-09-11 15:20:01Z)

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1736

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 17 Jun 2015 16:11 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 6 Nov 2015 09:53 UTC**
Also in v2.3.3.

**Comment by tobolar** [comment]
Does this only concern the documentation? I would anyway suggest to set 'print' as the last input as it only relates to html printing.

**Comment by beutlich** [comment]
No, `print` it is not only missing in the documentation of StateSpace.Plot.polesAndZeros, but when called in the algorithm of TransferFunction.Plot.polesAndZeros.

**Comment by tobolar** [comment]
Thank's, I will fix this.

**Comment by tobolar** [comment]
Obviously, this issue has already been solved before imported into github. I can't find any hint in the file history, see https://github.com/modelica/Modelica_LinearSystems2/commits/master/Modelica_LinearSystems2/TransferFunction.mo

**Comment by tbeu** [comment]
Hm, both problems are still there
* Missing print argument in function call: https://github.com/modelica/Modelica_LinearSystems2/blob/master/Modelica_LinearSystems2/TransferFunction.mo#L1564
* Missing print argument in function documentation: https://github.com/modelica/Modelica_LinearSystems2/blob/master/Modelica_LinearSystems2/StateSpace.mo#L7516

**Comment by tobolar** [comment]
Sorry, but I'm somehow confused about the function call issue.
I can really find no problem in [TransferFunction.Plot.polesAndZeros](https://github.com/modelica/Modelica_LinearSystems2/blob/98852df5c371d499e0c574f74c8a1606a07bc124/Modelica_LinearSystems2/TransferFunction.mo#L1570). 
There is just one function call in the algorithm block stating 
`StateSpace.Plot.polesAndZeros(StateSpace(tf), poles, zeros, defaultDiagram=defaultDiagram, device=device);` having both positional and named arguments.

**Comment by tbeu** [comment]
* Missing print argument in function call: https://github.com/modelica/Modelica_LinearSystems2/blob/7b83bbf22d7d0a2d5315c2bcc2953f69b863046c/Modelica_LinearSystems2/TransferFunction.mo#L1564
* Missing print argument in function documentation: https://github.com/modelica/Modelica_LinearSystems2/blob/7b83bbf22d7d0a2d5315c2bcc2953f69b863046c/Modelica_LinearSystems2/StateSpace.mo#L7516

**Comment by tbeu** [comment]
Ah, now I see. The missing print argument in the function call was fixed by 7406c5fea1c7655269485fb5736c0419c18f436a (for v2.3.3) by adding the named arguments.

**Comment by tobolar** [comment]
@tbeu Thank's for being patient with me. :-)
Concernig function documentation, I have fixed this in the commit #61. The print argument was falsely given as 'plot' in the syntax section.

So I think we can close this issue.
