### ISSUE TITLE
Utilize ModelicaIO functions for matrix I/O

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_LinearSystems2#34]
**Reported by beutlich on 14 Mar 2016 20:29 UTC**
Replace functions _readMatrixSize_, _readMatrix_ and _writeMatrix_ by open-source functions _Modelica.Utilities.Streams.readMatrixSize_, _readRealMatrix_ and _writeRealMatrix_, respectively.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1958

**Comment by tobolar** [comment]
Resolved on commit e5c69c262e9344301341e195160705149297e5e0.

**Comment by tobolar** [comment]
There are still some issues when reading a matrix of integers from a file.

**Comment by tbeu** [comment]
Ah, I believe it requires ModelicaMatIO v1.5.10 that will be part of the next MSL.

**Comment by tobolar** [comment]
Is it possible to obtain that ModelicaMatIO in advance to be possible to check the functionality? Or would you check on your own?

**Comment by tbeu** [comment]
You can take current ModelicaMatIO from MSL master branch. I can only check it in August when I habe my PC again.

**Comment by tobolar** [comment]
Great! It works using https://github.com/beutlich/Modelica/tree/update-binaries which is pull-requested in https://github.com/modelica/Modelica/pull/2273.

**Comment by tbeu** [comment]
This is not fixed yet.

**Comment by tobolar** [comment]
Would this fix automatically if MSL v3.2.3 releases?

**Comment by beutlich** [comment]
Yes, if it already does with current MSL v3.2.3-beta2.

**Comment by tobolar** [comment]
Thanks, I will check it.

**Comment by beutlich** [comment]
> 
> 
> Thanks, I will check it.

Did it work out then?
