### ISSUE TITLE
Invalid inheritance in M_LS2 icons

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_LinearSystems2#36]
**Reported by beutlich on 17 Aug 2016 09:33 UTC**
See [output.txt](https://github.com/modelica/Modelica_LinearSystems2/files/740230/output.txt) for the complete list of cases of invalid inheritance in LinearSystems2.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2046

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 31 Aug 2016 08:56 UTC**

**Comment by tobolar** [comment]
I would suggest to create necessary icon classes within Modelica_LinearSystems2.Utilities.Icons and use them within the Library.

**Comment by tbeu** [comment]
This is the current list of warnings: [output.txt](https://github.com/modelica/Modelica_LinearSystems2/files/1203416/output.txt)

**Comment by tobolar** [comment]
Resolved, see commit #58.

**Comment by tobolar** [comment]
Check this issue again.

**Comment by tobolar** [comment]
Inheritances of `operator records` were cleared in #58, esp. those leading to (cf. output.txt in https://github.com/modelica/Modelica_LinearSystems2/issues/36#issuecomment-320531805 above):
> ...ZerosAndPoles (operator record) and its base class Modelica.Icons.Record (record) are not compatible.

However, they were reintroduced in https://github.com/modelica/Modelica_LinearSystems2/commit/187059f5764ce1d9c3b806c1dd1e9fc63bb43569 again. My mistake, as I myself merged the corresponding PR #71.

But the Modelica specification clearly states (see 4.6 Specialized Classes):
> An operator record can only extend from an operator record [as short class definition, and not from another specialized class].

I'm going to eventually delete those invalid inheritances.
