### ISSUE TITLE
What branch will the next release be based on?

### ISSUE THREAD

**Issue by tbeu** [modelica/Modelica_LinearSystems2#59]
What branch will the next release be based on? Either master or version_2.3.5? It is currently not clear to me, also branches cannot be merged automatically due to conflicts.

**Comment by tobolar** [comment]
I'm going to release the next version 3.0.0 as commented in #39 - provided there is no other suggestion. Curently this version is marked as 2.3.5 for it was not clear to me how significant the future changes will be.

**Comment by tbeu** [comment]
Ah, right. Thanks.
