### ISSUE TITLE
Adapt new Modelica Association license (BSD-3 clause) 

### ISSUE THREAD

**Issue by beutlich** [modelica/Modelica_LinearSystems2#64]
The library is *Licensed by DLR under the Modelica License 2*. Since the library is within the `modelica` user group and therefore under the umbrella of the Modelica Association, the new licensing model of the Modelica Association should be adapted (i.e., BSD-3 clause). This would help for future integration into the Modelica Standard Library (MSL).

See also #33.

@christoff-buerger I copied the issue text from https://github.com/modelica/Modelica_Synchronous/issues/35.

**Comment by tobolar** [comment]
Is this not a duplicate of #33 indeed?

**Comment by beutlich** [comment]
It is not. #33 is on the licensor (DLR or MA), this one is on the license itself (BSD or MoLic2).

**Comment by MartinOtter** [comment]
O.k., please change license to BSD

**Comment by tobolar** [comment]
License changed in 9598e66dcd336daac8855a0521cfca50cb2c10af
