### ISSUE TITLE
Modelica_LinearSystems2.Math.Complex vs. Complex

### ISSUE THREAD

**Issue by beutlich** [modelica/Modelica_LinearSystems2#65]
Can utilize Complex of the MSL instead of a repeated definition in Modelica_LinearSystems2.Math.Complex.

**Comment by tobolar** [comment]
This is widely done in https://github.com/modelica/Modelica_LinearSystems2/tree/version_2.3.5 (which in fact should probably better be v3.0.0). But the progress is sticking now especially due to undecided https://github.com/modelica/Modelica_LinearSystems2/issues/32.

See also similar issue #38.

**Comment by beutlich** [comment]
> But the progress is sticking now especially due to undecided #32.

Looking at #32 again I see that it is assigned to @MartinOtter who should then initiate a decision.

**Comment by MartinOtter** [comment]
Sorry, I do not understand this ticket. As I understand, in #38 Modelica_LinearSystems2.Math.Complex was removed and the uses of Complex changed to package Complex of MSL (which is useful). Are there other issues with Complex?
