### ISSUE TITLE
Delete from_Hz and to_Hz from Modelica_LinearSystems2.Internal

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica_LinearSystems2#9]
**Modified by dietmarw on 22 Jun 2012 16:39 UTC**
Remove no more used classes 
 * `Modelica_LinearSystems2.Internal.from_Hz` 
 * `Modelica_LinearSystems2.Internal.to_Hz`
since the classes from Modelica.SIunits.Conversions are used instead.

Also don't forget to write conversion statements for upgrading purposes.

----

**Reported by tobolar on 22 Jun 2012 15:26 UTC**
Remove no more used classes Modelica_LinearSystems2.Internal.from_Hz and Modelica_LinearSystems2.Internal.to_Hz since the classes from Modelica.SIunits.Conversions are used instead.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/764

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 22 Jun 2012 16:39 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by tobolar on 25 Jun 2012 15:07 UTC**
The classes were marked as obsolete in b14c17d63d4aa46e92e8b08e685b92c2d0c98197 and the script for conversion was added as well.

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:36 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 1 Aug 2015 21:39 UTC**
Milestone renamed

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 14 Mar 2016 20:38 UTC**

**Comment by tobolar** [comment]
Conversion script added: 10641c41bf78fc1978c8d7d5a3fe8db8dc7f8407
